apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  selector:
    app: mysql-app
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None

# if used with statefulSet than don't need to specify subdomain and hostname