apiVersion: v1
kind: Pod
metadata:
  name: mysql-app
  labels:
    name: mysql-app
spec:
  containers:
  - name: mysql
    image: "mysql:latest"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
  subdomain: headless-service
  hostname: mysql-pod
