apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: dev
  labels:
    name: myapp
spec:
  containers:
  - name: nginxApp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"