apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: dev
  labels:
    name: myapp
spec:
  containers:
  - name: nginxApp
    image: nginx
    # command is like ENTRYPOINT in Dockerfile
    command: ["sleep"]
    # args is like CMD in Dockerfile.
    args: ["1000"]
    env:
      - name: YUVAL
        value: weber
    resources:
      requests:
        cpu: "125m"
        memory: "100mi"
      limits:
        memory: "128Mi"
        cpu: "500m"