apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: apache-custom
        # checks when container ready
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
        # check whether container should stay alive
        livenessProbe:
          exec:
            command:
              - python3.7
              - /var/liveness_probe.py
          initialDelaySeconds: 5
          periodSeconds: 30
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"