apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  ports:
    # the conatiner port
    - targetPort: 80
    # the service port
      port: 80
    # the port to open on the node
      nodePort: 30008
  selector:
    app: myapp