name: example github action react

# when the workflow should be triggered.
on:
  # on push to main branch
  push:
    branches: [main]
  # when merging with main branch
  pull_request:
    branches: [main]

# jobs to run
jobs:
  # job name
  build:
    # where job run. 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x,12.x,14.x]

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: Use node.js version ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    
    - run: |
        npm i
        npm run build --if-present
        npm test