apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
    # set all values from secret
      - secretRef:
          name: mysecret
  - name: myapp2
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    # set specific value from secret
      - name: password
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  # or inject secret as volume
  volumes:
    - name: mysecret-volume
      secret:
        secretName: mysecret

