apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
    - "system:authenticated"
  usages:
    - digital signature
    - key encipherment
    - server auth
  # request is base64 encode 
  signerName: kubernetes.io/kubelet-serving
  request:
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dqQ0NBVUlDQVFBd0ZURVRNQkVHQTFVRUF3d0tlWFYyWVd4M1pXSmxjakNDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1VGdEpNcG4xVzRYd0JKL0dsQ3RKbEpEZnRzcE5KOTNLeHc2Mk9LCkZwZERMMkY2enNpMnlrWmcvbGRpbEdLeFpKbnRET01hblUwQVNxcUxpWjlQRXRZVEEyejg1QVdYQm5DeC9Ld0QKTEsybm5ELzFCMUR6d01iY3ZKaXVrMzZSdHlGNVc2bDhrRlFXdzBZdkVEN1QvWks1NTBSWXVhNTFlLzdVSDRKMgp1eVAyNG4wckhQcDRHc2k1M2RMQzh0N3FFUnVCWTkzZDNnc2VQT1M5ZGs1dnNHclBGUVRVWm55QWVuc2ZVMkkzCncxalhmRFA0aFJ4ZUVmaGkxdmp5VFlmbWFvUEZDQ3RlanZhTWRFV1RZdStJWTFFUDdDbUdxUDN5N1paY3pRaFoKdlhEeVRpSzNOTmptQ1ZsNzNnWUFOVnZVcTZXaG5tM3NqQ3pEdlFLbm9TUy8wY1VDQXdFQUFhQUFNQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFDQzl6MUdubUlPMk5Sc04velNGTjlaZGJHdjdKYWFrdWcyUlFaeWFxYmF4MVgyClU1ZzB1eHFiWVJCdzFpYWFKbFpOWXZYdkNOMHNFOTRKT2drbDhtTUxhVkFuV0FaVzlFZnNWK0E5K0tTU0M5K3oKb2Z5RTBQb2sydFR1aTdpbXBMU2hMNE03dFcrNVV6azdKOXFFZ1Fyb2hsSk5vKy8wQUhCTXlmNWtqV2pab28vWApnb0pTOUk3Q04rNkxnaklERUNMQWVLVXR6RTF0Zm1uaVIxV29nclRYbTgvMkNuTUhsY2VodEhvY1AveXdaankyCkpJS1B2bnNCTytaQStpMkY2b2FKaUcyVTVQWmxxNElvZ2d2UnE5TXFZUU5SMVdlVktDVDNWRTJIc3dURExNQ0UKYzNVSkhzRGEya1dEenBHVG4vMUN6REZHdkRLbno5L252YW85NDVuNwotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K