version: '3'
services:
  postsproject:
    build:
      context: .
      dockerfile: Dockerfile
    image: postsproject:1.0
    container_name: express_proj
    depends_on:
      - mongo
    ports:
      - 80:80
    restart: always

  mongo:
    image: mongo:latest
    container_name: Mongo
    restart: always
